extends Node

# List IDs of supported cards here
var TREE = "TREE"
var HILL = "HILL"
var LOOK_AT_THE_SIZE_OF_THIS_TREE = "LOOKATTHESIZEOFTHISTREE"
var SWAMP = "SWAMP"
var NOM_NOM_PLANT = "NOMNOMPLANT"
var HUT = "HUT"
var SHOP = "SHOP"
var SKYSCRAPER = "SKYSCRAPER"
var TOTALLY_NOT_A_TRASH_PILE = "TOTALLYNOTATRASHPILE"
var FANCY_POWER_PLANT = "FANCYPOWERPLANT"
var ROCK = "ROCK"
var POND = "POND"
